apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      spec:
        containers:
          - name: auth-service
            image: korun/auth-service:latest
            ports:
              - containerPort: 8081
            env:
              - name: KORUN_KAFKA_BROKERS
                value: "kafka:9092"
              - name: KORUN_LOGGER_LEVEL
                value: "debug"
              - name: KORUN_LOGGER_FORMAT
                value: "json"
            livenessProbe:
              httpGet:
                path: /health
                port: 8081
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /health
                port: 8081
              initialDelaySeconds: 5
              periodSeconds: 10
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
