server:
  port: 8081
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

database:
  host: postgres
  port: 5432
  user: korun_user
  password: korun_password
  dbname: korun_db
  sslmode: disable
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 1h

jwt:
  access_secret: 12my-super-secret-jwt-key-change-in-production
  refresh_secret: 34my-super-refresh-token-secret-change-in-production
  access_token_ttl: 15m
  refresh_token_ttl: 168h # 7 days

infra:
  kafka:
    brokers:
      - kafka:29092
    auth_events: auth_events_topic
    retry_attempts: 3
    retry_backoff: 2s

  redis:
    host: redis
    port: 6379
    password:
    db: 0

  logger:
    level: debug
    format: json
